"""Limits shared by Program import readers and API schemas."""

from agent.program_prescription import MAX_GENERATED_TARGET_SETS

MAX_PROGRAM_IMPORT_FILE_BYTES = 1024 * 1024
MAX_PROGRAM_IMPORT_ROWS = 500
MAX_PROGRAM_IMPORT_COLUMNS = 64
MAX_PROGRAM_IMPORT_TABS = 20
MAX_PROGRAM_IMPORT_TAB_PROBE_ROWS = 100
MAX_PROGRAM_IMPORT_CELLS = 2000
MAX_PROGRAM_IMPORT_GRID_ROWS = 2000
MAX_PROGRAM_IMPORT_GRID_COLUMNS = 2000
MAX_PROGRAM_IMPORT_GRID_RECTANGLE = 500_000
MAX_PROGRAM_IMPORT_HEADER_SCAN_ROWS = MAX_PROGRAM_IMPORT_GRID_ROWS
MIN_PROGRAM_IMPORT_LAYOUT_CONFIDENCE = 0.75
MAX_PROGRAM_IMPORT_REST_SECONDS = 3600
MAX_PROGRAM_IMPORT_DAY_NAME_LENGTH = 100
MAX_PROGRAM_IMPORT_EXERCISE_NAME_LENGTH = 120
MAX_PROGRAM_IMPORT_SETS = MAX_GENERATED_TARGET_SETS
