"""Curated Exercise library vocabulary shared by curation and search."""

PRIMARY_MUSCLES = (
    "Chest",
    "Upper Chest",
    "Front Delts",
    "Side Delts",
    "Rear Delts",
    "Lats",
    "Upper Back",
    "Traps",
    "Lower Back",
    "Biceps",
    "Triceps",
    "Forearms",
    "Abs",
    "Obliques",
    "Quads",
    "Hamstrings",
    "Glutes",
    "Adductors",
    "Abductors",
    "Calves",
    "Neck",
    "Cardio",
)

PRIMARY_ACTIONS = (
    "Shoulder Flexion",
    "Shoulder Extension",
    "Shoulder Abduction",
    "Shoulder Adduction",
    "Shoulder Horizontal Adduction",
    "Shoulder Horizontal Abduction",
    "Shoulder External Rotation",
    "Shoulder Internal Rotation",
    "Scapular Elevation",
    "Scapular Retraction",
    "Scapular Depression",
    "Scapular Protraction",
    "Elbow Flexion",
    "Elbow Extension",
    "Wrist Flexion",
    "Wrist Extension",
    "Spinal Flexion",
    "Spinal Extension",
    "Spinal Rotation",
    "Spinal Lateral Flexion",
    "Anti-Extension",
    "Anti-Rotation",
    "Anti-Lateral Flexion",
    "Hip Flexion",
    "Hip Extension",
    "Hip Abduction",
    "Hip Adduction",
    "Knee Flexion",
    "Knee Extension",
    "Ankle Plantar Flexion",
    "Ankle Dorsiflexion",
    "Neck Flexion",
    "Neck Extension",
    "Conditioning",
)
