"""Shared prescription defaults and limits for program authoring."""

MIN_REPS = 4
MAX_REPS = 30
MIN_TARGET_RIR = 0.0
MAX_TARGET_RIR = 5.0

DEFAULT_TARGET_SETS = 2
DEFAULT_TARGET_REPS_MIN = 8
DEFAULT_TARGET_REPS_MAX = 12
DEFAULT_TARGET_RIR = 2.0

MIN_GENERATED_TARGET_SETS = 1
MAX_GENERATED_TARGET_SETS = 4
MIN_GENERATED_TARGET_RPE = 7.0
MIN_GENERATED_EXERCISES_PER_DAY = 3
MAX_EXERCISES_PER_DAY = 14
