"""Shared prescription defaults and limits for program authoring."""

MIN_REPS = 4
MAX_REPS = 30
MIN_TARGET_RIR = 0.0
MAX_TARGET_RIR = 5.0

DEFAULT_TARGET_SETS = 2
DEFAULT_TARGET_REPS_MIN = 8
DEFAULT_TARGET_REPS_MAX = 12
DEFAULT_TARGET_RIR = 2.0
DEFAULT_EXERCISE_REST_SECONDS = 180

DEFAULT_WARMUP_MOVEMENT_SETS = 2
DEFAULT_WARMUP_MOVEMENT_REPS = 10
DEFAULT_WARMUP_MOVEMENT_REST_SECONDS = 45
MIN_WARMUP_MOVEMENT_SETS = 1
MAX_WARMUP_MOVEMENT_SETS = 3
MIN_WARMUP_MOVEMENT_REPS = 5
MAX_WARMUP_MOVEMENT_REPS = 20

MIN_RAMPED_WARMUP_SETS = 0
MAX_RAMPED_WARMUP_SETS = 4
MAX_PROGRAM_DAYS = 5
MAX_TEMPO_LENGTH = 50
MAX_PROGRAM_NOTES_LENGTH = 2000

MIN_GENERATED_TARGET_SETS = 1
MAX_GENERATED_TARGET_SETS = 4
MIN_GENERATED_TARGET_RPE = 7.0
MIN_GENERATED_EXERCISES_PER_DAY = 3
MAX_EXERCISES_PER_DAY = 14
